apiVersion: v1
kind: ConfigMap
metadata:
  name: einbuchen-config-depl
data:
  MONGO_SERVER: "mongo"
  INTERFACE: "0.0.0.0"
  PORT: "8090"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: einbuchen-crest-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: einbuchen-crest-depl
      role: backend
      scs: einbuchen
  template:
    metadata:
      labels:
        app: einbuchen-crest-depl
        role: backend
        scs: einbuchen
    spec:
      initContainers:
      - name: config-creator-depl
        image: busybox
        envFrom:
        - configMapRef:
            name: einbuchen-config-depl
        command: ['/bin/sh', '-c', 'echo {\"mongoes\": {\"mongouri\": \"mongodb://$MONGO_SERVER:27017/einbuchen\"}, \"bind-interface\": \"$INTERFACE\", \"bind-port\": \"$PORT\"} > /config/config.json']
        volumeMounts:
         - name: config-volume-depl
           mountPath: /config
      containers:
      - name: crest-depl
        image: lars0395/einbuchen
        args:
        - -conf 
        - /etc/config/config.json
        ports:
        - containerPort: 8090
          protocol: TCP
        volumeMounts:
          - name: config-volume-depl
            mountPath: /etc/config
      volumes:
        - name: config-volume-depl
          emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: einbuchen-crest-depl
spec:
  ports:
  - port: 8090
    name: web
  selector:
    app: einbuchen-crest-depl
    role: backend
    scs: einbuchen
