apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "kubernetes-fluentd.fullname" . }}
  labels:
    app: {{ template "kubernetes-fluentd.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    kubernetes.io/cluster-service: "true"
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "kubernetes-fluentd.name" . }}
        kubernetes.io/cluster-service: "true"
    spec:
      serviceAccountName: {{ template "kubernetes-fluentd.fullname" . }}
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Equal
        effect: NoSchedule
      containers:
      - name: fluentd
        image: {{ .Values.image.repository }}:{{ required "please pass in docker image tag '--set image.tag=<docker-tag>'" .Values.image.tag }}
        env:
          # trigger error on missing stage: {{ required "please pass in stage with '--set stage={dev|prod}'" .Values.stage }}
          - name:  FLUENTD_CONF
            value: "k8s-mounted/fluentd.conf"
        resources:
          limits:
            memory: {{ .Values.memoryLimit }}
          requests:
            cpu: 100m
            memory: {{ .Values.memoryRequest }}
        volumeMounts:
        - name: fluentd
          mountPath: /fluentd/etc/k8s-mounted
        - name: varlog
          mountPath: /var/log
        - name: posfile
          mountPath: /var/log/fluentd
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      volumes:
      - name: fluentd
        configMap:
          name: {{ template "kubernetes-fluentd.fullname" . }}
          items:
          - key: fluentd.conf
            path: fluentd.conf
          - key: kubernetes.conf
            path: kubernetes.conf
      - name: varlog
        hostPath:
          path: /var/log
      - name: posfile
        hostPath:
          path: /var/log/fluentd
          type: DirectoryOrCreate
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
