---

apiVersion: v1
kind: Service
metadata:
  name: assets
  labels:
    app: assets
    role: frontend
    scs: assets
spec:
  ports:
  - port: 80
    name: web
  selector:
    app: assets
    role: frontend
    scs: assets

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: assets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assets
      role: frontend
      scs: assets
  template:
    metadata:
      labels:
        app: assets
        role: frontend
        scs: assets
    spec:
      containers:
      - name: nginx
        image: containerbootcamp/assets
        ports:
        - containerPort: 80
          name: web

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: assets
spec:
  rules:
  - host: trainer.ch.innoq.io
    http:
      paths:
      - path: /
        backend:
          serviceName: assets
          servicePort: 80